language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  email: olesya.sidyaka@gmail.com
  api_key:
    secure: JTSLGHMZGatu8hEBmRGVFpYEzNeuVxTLoq3Op+VaXiLVG5E06RJolxPgRb0IvjYMgzKJXVfPfWRh9u68qa5lsabs7CG9JLKp8ZaD5pBWuGRxIKmqQzgL7IPdHZUQkzyAfxQTnvfrUlSY8aU4cEE8wfiyi32D4Vn5WXTs9G6FHp1nqnFjTQm4Foh3aHXNgw0TMQg3eOu01XlYWZESxQGEmoIiHWRI0632Ufers714XGT8b7CqjL2E2fGOTXwxD2CyDhPXgJ/nTsDBAdE1rv2bzMd94BsxVHyOcnvT7W3inll6axLdmNJPkNEqaLOH8PxlvQWXKwEifgp4iuycRTMZdyE0whGoAtOaEQHqEpQs/drOPxjgs+1QUrhfl/Cm1f4GxQY2+6tTmfrm/s62mMfivNE3kfdPhqSOEtbdBQ1XgtV+iDLMRdiSpXvbwYjTXJPlfIhJqI9aH64L/Jxqr4R4STGqxeY205/9sb5mBwLQwZcRDjgXoF/137rW3LKjdlNdrnm5LQCaXAD0oGSx8R1LZgwJ3y2Hu34s3qDVjDautiswuesyGktpb8KJvXxcgenUQ4wpQMM7j7sbQD8DeETQrZSyBftNXq6RNspdMOwVqib4cZVQVli5AJqlkMvUQYRSQCUx4wx3jqe9VmPacGzW9jya5bknlUOpVYwLgku/eZI=
